server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://140.143.156.36:3306/miracle?useUnicode=true&characterEncoding=utf8&tinyInt1isBit=false&zeroDateTimeBehavior=convertToNull&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
