server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://139.199.102.31:3306/miracle?useUnicode=true&characterEncoding=utf8&tinyInt1isBit=false&zeroDateTimeBehavior=convertToNull&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

  mvc:
    view:
      prefix: /pages/
      suffix: .html
logging:
  config: classpath:log4j2.yml
mybatis:
  mapper-locations: classpath:mapper/*.xml


